# Generated by Django 5.0 on 2023-12-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_mood', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='timeline',
            new_name='Emp',
        ),
    ]
