# Generated by Django 5.0 on 2023-12-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('isStar', models.BooleanField(default='false')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
