# Generated by Django 5.0 on 2024-01-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_todo_rename_weapons_ta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ta',
            new_name='Task',
        ),
    ]
