# Generated by Django 5.0.1 on 2024-01-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_uploads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploads',
        ),
    ]
